SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE user (
	id INT NOT NULL,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL
);

CREATE TABLE News (
	id INT NOT NULL,
	title VARCHAR(100) NOT NULL,
	image VARCHAR(255) NOT NULL,
	deskripsi VARCHAR(255) NOT NULL,
	create_time TIME(0) NOT NULL,
	User_id INT NOT NULL);


ALTER TABLE 'user'
	ADD PRIMARY KEY ('id')

ALTER TABLE 'News'
	ADD PRIMARY KEY ('id')